name: armas
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=1.5.3
  - ipykernel=6.14.0
  - python=3.8.13
  - scikit-learn=1.2.2
  - seaborn=0.13.0
  - pip=23.3.1
  - scipy=1.10.1
  - notebook=7.0.6
  - ffmpeg=5.1.2
  - autogluon=0.8.2
  - pip:
    - scikit-image==0.19.3
    - fastapi==0.104.1
    - uvicorn==0.24.0.post1                
    - python-multipart==0.0.6
    - librosa==0.10.1
    - tensorflow==2.8.*