name: armas_app
description: "Unistar armas Mobile app frontend"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  flutter_sound: ^8.0.0+1
  permission_handler: ^8.0.0
  file_picker: ^4.2.0
  path_provider: ^2.0.2
  just_audio: ^0.9.0
  http: ^0.13.3
  fluttertoast: ^8.0.8
  video_player: ^2.2.14
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/armas.png"


flutter:
  uses-material-design: true
  assets:
    - assets/image/banner7.png
    - assets/image/armas.png
    - assets/image/access.png
    - assets/image/dost.png
    - assets/image/unistar.png
    - assets/video/banner_video.mp4
    - assets/video/ARMAS_video.mp4
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/font/bebas_neue/BebasNeue-Regular.ttf
        # Include other font weights if you have them
        # - asset: fonts/BebasNeue-Bold.ttf
        #   weight: 700
