services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"  # Longpolling port
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons  
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - ODOO_MASTER_PASSWORD=${ODOO_MASTER_PASSWORD}
    networks:
      - odoo-network

volumes:
  db-data:
  odoo-data:

networks:
  odoo-network: